server:
  port: 4445

base_url: http://localhost:4444

taxsystem_url: api/taxsystem

company_url: api/company

bankAccount_url: api/bank/account

contractorGroup_url: api/contractor/group

contractor_url: api/contractor

bankAccount_url: api/bank/account

role_url: api/role

attribute_calculation_object_url: api/attribute/calculation/object

contractor_group_url: api/contractor/group

contract_url: api/contract

department_url: api/department

employee_url: api/employee

image_url: api/image

position_url: api/position

productgroup_url: api/productgroup

product_url: api/product

typeofcontractor_url: api/typeofcontractor

typeofprice_url: api/typeofprice

unit_url: api/unit

warehouse_url: api/warehouse
