server:
  port: 4445

base_url: http://localhost:4444

tax_system_url: api/taxsystem

company_url: api/company

contractor_url: api/contractor

bank_account_url: api/bank/account

department_url: api/department
